name: Test & Lint & Publish

on:
  push:
    paths-ignore:
      - README.md
    branches: ["*"]
    tags: ["*"]
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
      - README.md

jobs:
  lintAndTest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        python -m pipenv install --dev --system
    - name: Lint
      run: black --check . && flake8 . && mypy --pretty  .
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    needs: ['lintAndTest']
    if: ${{ github.ref_type == 'tag' && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
